package org.viators.argo.common.exceptions;

public enum ErrorCodeEnum {
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    BUSINESS_VALIDATION_FAILED,
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    INVALID_STATE,
    VALIDATION_FAILED,
    DATA_INTEGRITY_VIOLATION,
    INTERNAL_SERVER_ERROR,
    CONFLICT,
    CONTENT_TOO_LARGE,
    STORAGE_ERROR,
    INVALID_PDF
}
